name:           TabSwapper
author:         anutron
#current:       0.1
category:       InterFace
tags:           [console, debug]
docs:           http://clientcide.com/docs/Layout/TabSwapper
demo:           http://www.clientcide.com/wiki/cnet-libraries/08-layout/05-tabswapper
#requires:
#   - { package: 'mootools-core', version: '1.2.3' }